[FEAT] Added unit tests setup
we-are-number-1/yumble pull request #235
Opened 2021-03-24 09:00 UTC by cecilia-yin

Closes #44

2021-03-24 09:07 UTC, David-Xia0 approved these changes
Nice, job finally got it running 😄

2021-03-24 09:12 UTC, blakehattingh commented
hey Cecilia the code looks great. Good job fixing the issue with the mock index. I think you have forgotten to add labels to the pull request as specified in the PR template. Once that is fixed i will approve

2021-03-24 09:13 UTC, blakehattingh commented
approved, nice work

2021-03-24 09:19 UTC, lilichenyuxin approved these changes

2021-03-24 09:19 UTC, lilichenyuxin commented
LGTM, nice work cici

2021-03-24 09:20 UTC, Jaysce approved these changes
LGTM

2021-03-24 09:26 UTC, blakehattingh commented on backend/src/routes/__tests__/sessions.test.js
> +      'price': 20,
I'm pretty sure this price is supposed to be between 1 and 4. Is this testing for a bug intentionally? if not please change to the accepted range

2021-03-24 09:35 UTC, blakehattingh submitted a review, later dismissed
legend, nice work

2021-03-24 09:45 UTC, Jaysce approved these changes
This is some clean code. I love clean code. 🧼

2021-03-24 09:56 UTC, Alxjlv commented
There's some stuff that's gone wrong with the testing. For one - the mocks in dist need to be ignored in jest:
![image](https://user-images.githubusercontent.com/44216323/112289964-a5b55c80-8cf3-11eb-8a1c-111d526b64b3.png)

Also, it appears that the tests are leaving some sockets disconnected and hanging open, which leaves the tests running continuously:
![image](https://user-images.githubusercontent.com/44216323/112290281-f2009c80-8cf3-11eb-9850-9ba104f7e4ce.png)

2021-03-24 09:58 UTC, Alxjlv commented
Maybe adding the `--detectOpenHandles` to jest in the package.json backend test script could help to troubleshoot why the test is hanging

2021-03-24 09:59 UTC, Alxjlv requested changes
The test suite needs to be fixed so that it doesn't hang for 20+ minutes

2021-03-25 04:46 UTC, Jaysce commented on backend/package.json
> +    "axios": "^0.21.1",
Maybe change this so that its a dev dependency instead.

2021-03-25 04:50 UTC, Jaysce approved these changes
Look good! Nice 👍

2021-03-25 04:51 UTC, lilichenyuxin approved these changes

2021-03-25 04:51 UTC, lilichenyuxin commented
LGTM

2021-03-25 04:53 UTC, Jaysce approved these changes
Changes have been done.

2021-03-25 04:54 UTC, BlinkCreator approved these changes
looks good

2021-03-25 04:58 UTC, Alxjlv approved these changes
👍

2021-03-25 04:59 UTC, merged