[WIKI] Modify Contributing on repo
we-are-number-1/yumble pull request #237
Opened 2021-03-24 09:23 UTC by BlinkCreator

2021-03-24 09:45 UTC, Alxjlv requested changes
Just a quick couple of changes!

2021-03-24 09:45 UTC, Alxjlv commented on CONTRIBUTING.md
> +A description of the [architecture](https://github.com/we-are-number-1/yumble/wiki/Yumble-Architecture-&-Design) can be found within the wiki. Backlog of aritecture can be found on the groups google-
What do you mean by backlog of architecture? Haha also, what is google-drive.git?

2021-03-24 09:45 UTC, Alxjlv commented on CONTRIBUTING.md
>  * Ask `se701group1@gmail.com` to be added as an outside collaborator
```suggestion
* Email `se701group1@gmail.com` in order to be added as an outside collaborator
```

2021-03-24 09:45 UTC, Alxjlv commented on CONTRIBUTING.md
>  * Node 15.x
```suggestion
* Node 15.11
```
I think a higher minor version of node broke it

2021-03-24 21:00 UTC, David-Xia0 approved these changes
Yeah see Alexs comment / change request
but apart from that LGTM

2021-03-25 04:59 UTC, Alxjlv approved these changes
👍

2021-03-25 05:51 UTC, Jaysce approved these changes
LGTM 👍

2021-03-25 06:19 UTC, merged