[FEAT] Feature/add expiry to mongodb documents
we-are-number-1/yumble pull request #279
Opened 2021-04-08 05:51 UTC by parfei

Add an expiry value to the `Session` MongoDB schema model, the value being one week (in seconds).
This value can be adjusted via `config.js` easily.

Closes # 278

2021-04-08 06:29 UTC, UltimaKuma requested changes
It seems as though these commits were branched off of someone elses commits rather than main2. Was this on purpose?

2021-04-08 06:29 UTC, UltimaKuma commented on backend/.env.example
> +# This file contains the variable names that are required for your .env file.
Was this branched off of seif's commit?

2021-04-08 06:29 UTC, UltimaKuma commented on frontend/src/components/7.Result/ResultPage.css
> -    -webkit-text-stroke: 4px black;
Why was this changed? It seems more than a formatting change

2021-04-08 06:37 UTC, UltimaKuma commented
Figured it out, its due to merging into main rather than main2, should fix this.

2021-04-08 06:53 UTC, parfei commented
If you would like to test that the expiry works, you can use the `testDatabase` instance I have set up in our Cluster. I've just been running the game until we get to the part where we choose our restaurant choices...I disconnect then and just wait until the document has been deleted from `testDatabase`.

Note that MongoDB expired document checks are based on a 60 second cycle

2021-04-08 07:13 UTC, UltimaKuma approved these changes
LGTM though is the reason we have to use testDatabase because myFirstDatabase is incorrectly setup?

Also in terms of tests, it could defs be something to think about on Sunday.

2021-04-08 07:16 UTC, parfei commented
> LGTM though is the reason we have to use testDatabase because myFirstDatabase is incorrectly setup?
> 
> Also in terms of tests, it could defs be something to think about on Sunday.

We just made `testDatabase` for testing purposes, so we can clearly see what is being added to it, etc. since we did not want to touch the documents in the `myFirstDatabase`. Is that okay? I can always delete the database

2021-04-08 07:28 UTC, UltimaKuma commented
> > LGTM though is the reason we have to use testDatabase because myFirstDatabase is incorrectly setup?
> > Also in terms of tests, it could defs be something to think about on Sunday.
> 
> We just made `testDatabase` for testing purposes, so we can clearly see what is being added to it, etc. since we did not want to touch the documents in the `myFirstDatabase`. Is that okay? I can always delete the database

It seems as though the ones i try to persist on myFirstDatabase with a reduced session_expiry arent being removed. While we could just migrate to testDatabase, it might be good to look into this issue

2021-04-08 08:17 UTC, parfei commented
> > > LGTM though is the reason we have to use testDatabase because myFirstDatabase is incorrectly setup?
> > > Also in terms of tests, it could defs be something to think about on Sunday.
> > 
> > 
> > We just made `testDatabase` for testing purposes, so we can clearly see what is being added to it, etc. since we did not want to touch the documents in the `myFirstDatabase`. Is that okay? I can always delete the database
> 
> It seems as though the ones i try to persist on myFirstDatabase with a reduced session_expiry arent being removed. While we could just migrate to testDatabase, it might be good to look into this issue

Thanks a lot for checking this :) Learnt that I should always check back with a database that's been untampered with.
It was not expiring on `myFirstDatabase` because an index for the `createdAt` TTL field was never created. But now it has been created, all you need to do is set the `expires` value (in the schema) to be a string and MongoDB does that for you.
![image](https://user-images.githubusercontent.com/42878423/113992239-5a7c7b80-98a7-11eb-91d5-f02fb6ea2829.png)

2021-04-08 09:57 UTC, jteo97 approved these changes
Great, it works.

2021-04-09 09:46 UTC, UltimaKuma approved these changes
LGTM, works fine with "myFirstDatabase". Nice!

2021-04-09 09:49 UTC, merged